networks:
    monitor-net:
        driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:          
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        ports:
            - 9090:9090
        networks:
            - monitor-net
        extra_hosts:
            - "host.docker.internal:host-gateway"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/provisioning:/etc/grafana/provisioning
            - grafana_data:/grafana
        restart: unless-stopped
        ports:
            - 3000:3000
        links:
            - prometheus
        networks:
            - monitor-net


